{{- if .Values.initializationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-initialization
  namespace: {{ .Release.Namespace }}
{{- with .Values.initializationFilesAnnotation }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.initializationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}