name: Check Helm Chart Migration

on:
  push:

jobs:
  check-migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Checkout banzaicloud/banzai-charts at tag cadence/0.24.1
      uses: actions/checkout@v2
      with:
        repository: banzaicloud/banzai-charts
        ref: cadence/0.24.2
        path: banzai-charts

    - name: Compare Helm Charts excluding README.md
      run: |
        for file in $(find banzai-charts/cadence -type f ! -name "README.md"); do
          relative_path=${file#banzai-charts/cadence/}
          diff "$file" "charts/cadence/$relative_path" || { echo "Difference found in $file"; exit 1; }
        done

    - name: Compare CI Pipeline
      run: |
        diff .github/workflows/ci.yaml banzai-charts/.github/workflows/ci.yaml || { echo "CI pipelines are not identical!"; exit 1; }
