name: Helm Continuous Integration
on:
  push:
    branches: "main"
  pull_request:

env:
    HELM_VERSION: 3.12.1
    PYTHON_VERSION: 3.11

jobs:
  helm:
    name: Chart Linting And Testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
            version: ${{ env.HELM_VERSION }}

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
        with:
          version: v3.9.0

      - name: Lint chart
        run: ct lint --all --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        run: |
          ct install --all --config ct.yaml --helm-extra-args="--timeout 10m"
